//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRA.Jobs.Application.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorMessageEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorMessageEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRA.Jobs.Application.Contracts.Resources.ValidatorMessageEnglish", typeof(ValidatorMessageEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicantUserName.
        /// </summary>
        internal static string ApplicantUserName {
            get {
                return ResourceManager.GetString("ApplicantUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationDeadline.
        /// </summary>
        internal static string ApplicationDeadline {
            get {
                return ResourceManager.GetString("ApplicationDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryId.
        /// </summary>
        internal static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoverLetter.
        /// </summary>
        internal static string CoverLetter {
            get {
                return ResourceManager.GetString("CoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        internal static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishDate.
        /// </summary>
        internal static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortDescription.
        /// </summary>
        internal static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        internal static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusId.
        /// </summary>
        internal static string StatusId {
            get {
                return ResourceManager.GetString("StatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stipend.
        /// </summary>
        internal static string Stipend {
            get {
                return ResourceManager.GetString("Stipend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VacancySlug.
        /// </summary>
        internal static string VacancySlug {
            get {
                return ResourceManager.GetString("VacancySlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSchedule.
        /// </summary>
        internal static string WorkSchedule {
            get {
                return ResourceManager.GetString("WorkSchedule", resourceCulture);
            }
        }
    }
}
