//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRA.Jobs.Client.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRA.Jobs.Client.Resources.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Dashboard_Appilcations_Action {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant response.
        /// </summary>
        internal static string Dashboard_Appilcations_Applicant_response {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applicant response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant username.
        /// </summary>
        internal static string Dashboard_Appilcations_Applicant_username {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applicant username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string Dashboard_Appilcations_Applications {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied at.
        /// </summary>
        internal static string Dashboard_Appilcations_Applied_at {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applied at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoverLetter.
        /// </summary>
        internal static string Dashboard_Appilcations_CoverLetter {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:CoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string Dashboard_Appilcations_More {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download applicant CV.
        /// </summary>
        internal static string Dashboard_Appilcations_More_CVButton {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:More:CVButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Dashboard_Appilcations_Name {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        internal static string Dashboard_Appilcations_Slug {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status name.
        /// </summary>
        internal static string Dashboard_Appilcations_Status_name {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Status name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusName.
        /// </summary>
        internal static string Dashboard_Appilcations_StatusName {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancy title.
        /// </summary>
        internal static string Dashboard_Appilcations_Vacancy_title {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Vacancy title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VacancyResponses.
        /// </summary>
        internal static string Dashboard_Appilcations_VacancyResponses {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:VacancyResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy.
        /// </summary>
        internal static string Header_Academy {
            get {
                return ResourceManager.GetString("Header:Academy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Header_Home {
            get {
                return ResourceManager.GetString("Header:Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internships.
        /// </summary>
        internal static string Header_Internships {
            get {
                return ResourceManager.GetString("Header:Internships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Header_Jobs {
            get {
                return ResourceManager.GetString("Header:Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Header_Team {
            get {
                return ResourceManager.GetString("Header:Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings.
        /// </summary>
        internal static string Header_Trainings {
            get {
                return ResourceManager.GetString("Header:Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Home_About {
            get {
                return ResourceManager.GetString("Home:About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Silk Road Professionals (SRP) is a full-cycle software development company founded in 2014. We are legally registered in Virginia, USA and in Dehmoy, Tajikistan..
        /// </summary>
        internal static string Home_AboutContent {
            get {
                return ResourceManager.GetString("Home:AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silk Road Professionals.
        /// </summary>
        internal static string Home_AboutTitle {
            get {
                return ResourceManager.GetString("Home:AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Home_Address {
            get {
                return ResourceManager.GetString("Home:Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugd, Jabbor Rasulov district,.
        /// </summary>
        internal static string Home_Address_p1 {
            get {
                return ResourceManager.GetString("Home:Address_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dehmoy, 80 Somoni Steet.
        /// </summary>
        internal static string Home_Address_p2 {
            get {
                return ResourceManager.GetString("Home:Address_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agile.
        /// </summary>
        internal static string Home_Agile {
            get {
                return ResourceManager.GetString("Home:Agile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our highest priority is to satisfy the customer through early and continuous delivery of valuable software..
        /// </summary>
        internal static string Home_AgileDetails {
            get {
                return ResourceManager.GetString("Home:AgileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string Home_Apps {
            get {
                return ResourceManager.GetString("Home:Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Amazing.
        /// </summary>
        internal static string Home_BuildAmazing {
            get {
                return ResourceManager.GetString("Home:BuildAmazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Always on the lookout for the hi-tech advancements. Build not only a product that can sell well, but a platform through which to deliver it..
        /// </summary>
        internal static string Home_BuildAmazing_Content_ {
            get {
                return ResourceManager.GetString("Home:BuildAmazing_Content.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string Home_Client {
            get {
                return ResourceManager.GetString("Home:Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  We build and run scalable applications with cloud computing..
        /// </summary>
        internal static string Home_CloudServiceDescription {
            get {
                return ResourceManager.GetString("Home:CloudServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Native Development.
        /// </summary>
        internal static string Home_CloudServiceTitle {
            get {
                return ResourceManager.GetString("Home:CloudServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Quality.
        /// </summary>
        internal static string Home_CodeQuality {
            get {
                return ResourceManager.GetString("Home:CodeQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do our best to write Descriptive Maintainable Economical Testable code..
        /// </summary>
        internal static string Home_CodeQualityDetails {
            get {
                return ResourceManager.GetString("Home:CodeQualityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Home_Contact {
            get {
                return ResourceManager.GetString("Home:Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continual Learning.
        /// </summary>
        internal static string Home_ContinualLearning {
            get {
                return ResourceManager.GetString("Home:ContinualLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  We are committed to keeping our skills and knowledge up to date so, that we can meet the requirements of our clients..
        /// </summary>
        internal static string Home_ContinualLearningDetails {
            get {
                return ResourceManager.GetString("Home:ContinualLearningDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string Home_Design {
            get {
                return ResourceManager.GetString("Home:Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  We build applications for an OS of your need..
        /// </summary>
        internal static string Home_DesktopServiceDescription {
            get {
                return ResourceManager.GetString("Home:DesktopServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Applications.
        /// </summary>
        internal static string Home_DesktopServiceTitle {
            get {
                return ResourceManager.GetString("Home:DesktopServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string Home_Development {
            get {
                return ResourceManager.GetString("Home:Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Us.
        /// </summary>
        internal static string Home_Email {
            get {
                return ResourceManager.GetString("Home:Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@silkroadprofessionals.com.
        /// </summary>
        internal static string Home_EmailLink {
            get {
                return ResourceManager.GetString("Home:EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glorify God.
        /// </summary>
        internal static string Home_GlorifyGod {
            get {
                return ResourceManager.GetString("Home:GlorifyGod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want everything we do to bring glory to God..
        /// </summary>
        internal static string Home_GlorifyGodDetails {
            get {
                return ResourceManager.GetString("Home:GlorifyGodDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Developer Softwate and Provide Outsourse Programming support..
        /// </summary>
        internal static string Home_Hero_Content {
            get {
                return ResourceManager.GetString("Home:Hero_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are here..
        /// </summary>
        internal static string Home_Hero_Title_1 {
            get {
                return ResourceManager.GetString("Home:Hero_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   To help you!.
        /// </summary>
        internal static string Home_Hero_Title_2 {
            get {
                return ResourceManager.GetString("Home:Hero_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How.
        /// </summary>
        internal static string Home_How {
            get {
                return ResourceManager.GetString("Home:How", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrinsic Control.
        /// </summary>
        internal static string Home_IntrinsicControl {
            get {
                return ResourceManager.GetString("Home:IntrinsicControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We encourage our programmers to be self-motivated towards improving their own skills and producing quality work..
        /// </summary>
        internal static string Home_IntrinsicControlDetails {
            get {
                return ResourceManager.GetString("Home:IntrinsicControlDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet.
        /// </summary>
        internal static string Home_Meet {
            get {
                return ResourceManager.GetString("Home:Meet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To engage a team of local talented IT professionals and empower them to deliver outstanding IT services to our partners.
        /// </summary>
        internal static string Home_MissionContent {
            get {
                return ResourceManager.GetString("Home:MissionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR MISSION.
        /// </summary>
        internal static string Home_MissionTitle {
            get {
                return ResourceManager.GetString("Home:MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We build a native and cross platform mobile applications..
        /// </summary>
        internal static string Home_MobileServiceDescription {
            get {
                return ResourceManager.GetString("Home:MobileServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Development.
        /// </summary>
        internal static string Home_MobileServiceTitle {
            get {
                return ResourceManager.GetString("Home:MobileServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Our Team.
        /// </summary>
        internal static string Home_OurTeam {
            get {
                return ResourceManager.GetString("Home:OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  And Partner Testimonials.
        /// </summary>
        internal static string Home_Partner {
            get {
                return ResourceManager.GetString("Home:Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        internal static string Home_Planning {
            get {
                return ResourceManager.GetString("Home:Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main principles.
        /// </summary>
        internal static string Home_Principles {
            get {
                return ResourceManager.GetString("Home:Principles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity.
        /// </summary>
        internal static string Home_Productivity {
            get {
                return ResourceManager.GetString("Home:Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  We are committed to providing the tools and environment that our programmers need to reach maximum productivity..
        /// </summary>
        internal static string Home_ProductivityDetails {
            get {
                return ResourceManager.GetString("Home:ProductivityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Us.
        /// </summary>
        internal static string Home_Us {
            get {
                return ResourceManager.GetString("Home:Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Team.
        /// </summary>
        internal static string Home_ViewTeam {
            get {
                return ResourceManager.GetString("Home:ViewTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To drive our business partners to a new level of success by providing remarkable IT outsourcing and outstaffing services.
        /// </summary>
        internal static string Home_VisionContent {
            get {
                return ResourceManager.GetString("Home:VisionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR VISION.
        /// </summary>
        internal static string Home_VisionTitle {
            get {
                return ResourceManager.GetString("Home:VisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We develop websites and enterprise web applications..
        /// </summary>
        internal static string Home_WebServiceDescription {
            get {
                return ResourceManager.GetString("Home:WebServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Development.
        /// </summary>
        internal static string Home_WebServiceTitle {
            get {
                return ResourceManager.GetString("Home:WebServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  We Do.
        /// </summary>
        internal static string Home_WeDo {
            get {
                return ResourceManager.GetString("Home:WeDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  We Work.
        /// </summary>
        internal static string Home_WeWork {
            get {
                return ResourceManager.GetString("Home:WeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What.
        /// </summary>
        internal static string Home_What {
            get {
                return ResourceManager.GetString("Home:What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        internal static string Home_WorkingHours {
            get {
                return ResourceManager.GetString("Home:WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon: 12pm to 9pm.
        /// </summary>
        internal static string Home_WorkingHours1 {
            get {
                return ResourceManager.GetString("Home:WorkingHours1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue - Fri: 8am to 5:30pm.
        /// </summary>
        internal static string Home_WorkingHours2 {
            get {
                return ResourceManager.GetString("Home:WorkingHours2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat - Sun: closed.
        /// </summary>
        internal static string Home_WorkingHours3 {
            get {
                return ResourceManager.GetString("Home:WorkingHours3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internships.
        /// </summary>
        internal static string Internships_Internships {
            get {
                return ResourceManager.GetString("Internships:Internships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Jobs_Jobs {
            get {
                return ResourceManager.GetString("Jobs:Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Myself.
        /// </summary>
        internal static string Profile_AboutMyself {
            get {
                return ResourceManager.GetString("Profile:AboutMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Education.
        /// </summary>
        internal static string Profile_AddNewEducation {
            get {
                return ResourceManager.GetString("Profile:AddNewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Experience.
        /// </summary>
        internal static string Profile_AddNewExperience {
            get {
                return ResourceManager.GetString("Profile:AddNewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skill.
        /// </summary>
        internal static string Profile_AddSkill {
            get {
                return ResourceManager.GetString("Profile:AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Profile_Cancel {
            get {
                return ResourceManager.GetString("Profile:Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code sent.
        /// </summary>
        internal static string Profile_Codesent {
            get {
                return ResourceManager.GetString("Profile:Codesent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Profile_CompanyName {
            get {
                return ResourceManager.GetString("Profile:CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Profile_Confirm {
            get {
                return ResourceManager.GetString("Profile:Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code.
        /// </summary>
        internal static string Profile_Confirmationcode {
            get {
                return ResourceManager.GetString("Profile:Confirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string Profile_Confirmed {
            get {
                return ResourceManager.GetString("Profile:Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Job.
        /// </summary>
        internal static string Profile_CurrentJob {
            get {
                return ResourceManager.GetString("Profile:CurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string Profile_DateOfBirth {
            get {
                return ResourceManager.GetString("Profile:DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Profile_Description {
            get {
                return ResourceManager.GetString("Profile:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educations.
        /// </summary>
        internal static string Profile_Educations {
            get {
                return ResourceManager.GetString("Profile:Educations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not Confirmed!.
        /// </summary>
        internal static string Profile_EmailisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:EmailisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string Profile_Experience {
            get {
                return ResourceManager.GetString("Profile:Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        internal static string Profile_Experiences {
            get {
                return ResourceManager.GetString("Profile:Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Profile_FirstName {
            get {
                return ResourceManager.GetString("Profile:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to nominate yourself, send us your СV..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_sendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,sendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  If you would like to nominate yourself, sign in and send us your СV..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_signinandsendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,signinandsendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Current Job.
        /// </summary>
        internal static string Profile_IsCurrentJob {
            get {
                return ResourceManager.GetString("Profile:IsCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string Profile_JobTitle {
            get {
                return ResourceManager.GetString("Profile:JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Profile_LastName {
            get {
                return ResourceManager.GetString("Profile:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Profile_MyProfile {
            get {
                return ResourceManager.GetString("Profile:MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Education.
        /// </summary>
        internal static string Profile_NewEducation {
            get {
                return ResourceManager.GetString("Profile:NewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Experience.
        /// </summary>
        internal static string Profile_NewExperience {
            get {
                return ResourceManager.GetString("Profile:NewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string Profile_OldPassword {
            get {
                return ResourceManager.GetString("Profile:OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string Profile_PersonalInformation {
            get {
                return ResourceManager.GetString("Profile:PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is not Confirmed!.
        /// </summary>
        internal static string Profile_PhoneNumberisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:PhoneNumberisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string Profile_Present {
            get {
                return ResourceManager.GetString("Profile:Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Profile_Save {
            get {
                return ResourceManager.GetString("Profile:Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string Profile_Savechanges {
            get {
                return ResourceManager.GetString("Profile:Savechanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string Profile_SelectLanguage {
            get {
                return ResourceManager.GetString("Profile:SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not responding.
        /// </summary>
        internal static string Profile_Serverisnotresponding {
            get {
                return ResourceManager.GetString("Profile:Serverisnotresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Profile_Skills {
            get {
                return ResourceManager.GetString("Profile:Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        internal static string Profile_Specialty {
            get {
                return ResourceManager.GetString("Profile:Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Profile_StartDate {
            get {
                return ResourceManager.GetString("Profile:StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Switch to Dark Theme.
        /// </summary>
        internal static string Profile_SwitchtoDarkTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Switch to Light Theme.
        /// </summary>
        internal static string Profile_SwitchtoLightTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Switch to system.
        /// </summary>
        internal static string Profile_Switchtosystem {
            get {
                return ResourceManager.GetString("Profile:Switchtosystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The status of your CV for your candidacy is.
        /// </summary>
        internal static string Profile_ThestatusofyourCVforyourcandidacyis {
            get {
                return ResourceManager.GetString("Profile:ThestatusofyourCVforyourcandidacyis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change your password, enter your old password, and then create a new, strong password..
        /// </summary>
        internal static string Profile_Tochangeyourpassword_enteryouroldpassword_andthencreateanew_strongpassword_ {
            get {
                return ResourceManager.GetString("Profile:Tochangeyourpassword,enteryouroldpassword,andthencreateanew,strongpasswor" +
                        "d.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string Profile_TryAgain {
            get {
                return ResourceManager.GetString("Profile:TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        internal static string Profile_University {
            get {
                return ResourceManager.GetString("Profile:University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until Now.
        /// </summary>
        internal static string Profile_UntilNow {
            get {
                return ResourceManager.GetString("Profile:UntilNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Profile_Update {
            get {
                return ResourceManager.GetString("Profile:Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload CV.
        /// </summary>
        internal static string Profile_UploadCV {
            get {
                return ResourceManager.GetString("Profile:UploadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Upload New CV.
        /// </summary>
        internal static string Profile_UploadNewCV {
            get {
                return ResourceManager.GetString("Profile:UploadNewCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ResetPassword_Changepassword {
            get {
                return ResourceManager.GetString("ResetPassword:Changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string ResetPassword_NewPassword {
            get {
                return ResourceManager.GetString("ResetPassword:NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string ResetPassword_PhoneNumber {
            get {
                return ResourceManager.GetString("ResetPassword:PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        internal static string ResetPassword_Resendcode {
            get {
                return ResourceManager.GetString("ResetPassword:Resendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send confirmation code.
        /// </summary>
        internal static string ResetPassword_Sendconfirmationcode {
            get {
                return ResourceManager.GetString("ResetPassword:Sendconfirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string SendCV_Close {
            get {
                return ResourceManager.GetString("SendCV:Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover letter.
        /// </summary>
        internal static string SendCV_CoverLetter {
            get {
                return ResourceManager.GetString("SendCV:CoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload your CV.
        /// </summary>
        internal static string SendCV_IfFileNull {
            get {
                return ResourceManager.GetString("SendCV:IfFileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send us your CV.
        /// </summary>
        internal static string SendCV_Title {
            get {
                return ResourceManager.GetString("SendCV:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        internal static string SendCV_Your_name {
            get {
                return ResourceManager.GetString("SendCV:Your name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number.
        /// </summary>
        internal static string SendCV_Your_phone_number {
            get {
                return ResourceManager.GetString("SendCV:Your phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Go to.
        /// </summary>
        internal static string SignIn_LabelDontAccount {
            get {
                return ResourceManager.GetString("SignIn:LabelDontAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string SignIn_LabelForgot {
            get {
                return ResourceManager.GetString("SignIn:LabelForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string SignIn_LinkReset {
            get {
                return ResourceManager.GetString("SignIn:LinkReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignIn_LinkSignUp {
            get {
                return ResourceManager.GetString("SignIn:LinkSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignIn_Password {
            get {
                return ResourceManager.GetString("SignIn:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn_SignIn {
            get {
                return ResourceManager.GetString("SignIn:SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string SignIn_UserName {
            get {
                return ResourceManager.GetString("SignIn:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string SignUp_Apply {
            get {
                return ResourceManager.GetString("SignUp:Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string SignUp_ButtonNext {
            get {
                return ResourceManager.GetString("SignUp:ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string SignUp_Code {
            get {
                return ResourceManager.GetString("SignUp:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string SignUp_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string SignUp_ConfirmPassword_HelperText {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp:Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue With.
        /// </summary>
        internal static string SignUp_ExternalLoginCard {
            get {
                return ResourceManager.GetString("SignUp:ExternalLoginCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firs name.
        /// </summary>
        internal static string SignUp_FirstName {
            get {
                return ResourceManager.GetString("SignUp:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        internal static string SignUp_FirstName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:FirstName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have an account? Go to.
        /// </summary>
        internal static string SignUp_LabelHaveAccount {
            get {
                return ResourceManager.GetString("SignUp:LabelHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp_LabelSignUp {
            get {
                return ResourceManager.GetString("SignUp:LabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name name.
        /// </summary>
        internal static string SignUp_LastName {
            get {
                return ResourceManager.GetString("SignUp:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        internal static string SignUp_LastName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:LastName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sign In.
        /// </summary>
        internal static string SignUp_LinkSignIn {
            get {
                return ResourceManager.GetString("SignUp:LinkSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a confirmation code to this number: $phone$. Please confirm your identity.
        /// </summary>
        internal static string signUp_messageText {
            get {
                return ResourceManager.GetString("signUp:messageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignUp_Password_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Password_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string SignUp_Phone {
            get {
                return ResourceManager.GetString("SignUp:Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        internal static string SignUp_Phone_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Phone_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        internal static string SignUp_ResendCode {
            get {
                return ResourceManager.GetString("SignUp:ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds left to resend the code..
        /// </summary>
        internal static string SignUp_Secconds {
            get {
                return ResourceManager.GetString("SignUp:Secconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string SignUp_UserName {
            get {
                return ResourceManager.GetString("SignUp:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings.
        /// </summary>
        internal static string Trainings_Trainings {
            get {
                return ResourceManager.GetString("Trainings:Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string UserButton_Applications {
            get {
                return ResourceManager.GetString("UserButton:Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string UserButton_Logout {
            get {
                return ResourceManager.GetString("UserButton:Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string UserButton_Profile {
            get {
                return ResourceManager.GetString("UserButton:Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string UserButton_Sign_In {
            get {
                return ResourceManager.GetString("UserButton:Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string UserButton_Sign_Up {
            get {
                return ResourceManager.GetString("UserButton:Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string VacanciesList_All {
            get {
                return ResourceManager.GetString("VacanciesList:All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string VacanciesList_Deadline {
            get {
                return ResourceManager.GetString("VacanciesList:Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string VacanciesList_Duration {
            get {
                return ResourceManager.GetString("VacanciesList:Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string VacanciesList_End_date {
            get {
                return ResourceManager.GetString("VacanciesList:End date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        internal static string VacanciesList_month_s_ {
            get {
                return ResourceManager.GetString("VacanciesList:month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no job vacancies available. Please check back later :).
        /// </summary>
        internal static string VacanciesList_NoJobs {
            get {
                return ResourceManager.GetString("VacanciesList:NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        internal static string VacanciesList_Posted {
            get {
                return ResourceManager.GetString("VacanciesList:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string VacanciesList_Search {
            get {
                return ResourceManager.GetString("VacanciesList:Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Details.
        /// </summary>
        internal static string VacancyApplication_Additional_Details {
            get {
                return ResourceManager.GetString("VacancyApplication:Additional Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string VacancyApplication_Apply {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply using profile.
        /// </summary>
        internal static string VacancyApplication_Apply_using_profile {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply using profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply with uploading file.
        /// </summary>
        internal static string VacancyApplication_Apply_with_uploading_file {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply with uploading file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Letter.
        /// </summary>
        internal static string VacancyApplication_Cover_Letter {
            get {
                return ResourceManager.GetString("VacancyApplication:Cover Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string VacancyApplication_Deadline {
            get {
                return ResourceManager.GetString("VacancyApplication:Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string VacancyApplication_Duration {
            get {
                return ResourceManager.GetString("VacancyApplication:Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string VacancyApplication_End_Date {
            get {
                return ResourceManager.GetString("VacancyApplication:End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        internal static string VacancyApplication_Fees {
            get {
                return ResourceManager.GetString("VacancyApplication:Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        internal static string VacancyApplication_month_s_ {
            get {
                return ResourceManager.GetString("VacancyApplication:month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        internal static string VacancyApplication_Posted {
            get {
                return ResourceManager.GetString("VacancyApplication:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string VacancyApplication_Processing {
            get {
                return ResourceManager.GetString("VacancyApplication:Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string VacancyApplication_Questions {
            get {
                return ResourceManager.GetString("VacancyApplication:Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required year of experience.
        /// </summary>
        internal static string VacancyApplication_Required_year_of_experience {
            get {
                return ResourceManager.GetString("VacancyApplication:Required year of experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your CV.
        /// </summary>
        internal static string VacancyApplication_Upload_your_CV {
            get {
                return ResourceManager.GetString("VacancyApplication:Upload your CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancy Details.
        /// </summary>
        internal static string VacancyApplication_Vacancy_Details {
            get {
                return ResourceManager.GetString("VacancyApplication:Vacancy Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year(s).
        /// </summary>
        internal static string VacancyApplication_year_s_ {
            get {
                return ResourceManager.GetString("VacancyApplication:year(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string VacancyDetails_Already_have_an_account_ {
            get {
                return ResourceManager.GetString("VacancyDetails:Already have an account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Now.
        /// </summary>
        internal static string VacancyDetails_Apply_Now {
            get {
                return ResourceManager.GetString("VacancyDetails:Apply Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready to take your career to the next level with.
        /// </summary>
        internal static string VacancyDetails_Are_you_ready_to_take_your_career_to_the_next_level_with {
            get {
                return ResourceManager.GetString("VacancyDetails:Are you ready to take your career to the next level with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string VacancyDetails_Deadline {
            get {
                return ResourceManager.GetString("VacancyDetails:Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download CV.
        /// </summary>
        internal static string VacancyDetails_Download_CV {
            get {
                return ResourceManager.GetString("VacancyDetails:Download CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string VacancyDetails_Duration {
            get {
                return ResourceManager.GetString("VacancyDetails:Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string VacancyDetails_End_Date {
            get {
                return ResourceManager.GetString("VacancyDetails:End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string VacancyDetails_Explore {
            get {
                return ResourceManager.GetString("VacancyDetails:Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        internal static string VacancyDetails_Fees {
            get {
                return ResourceManager.GetString("VacancyDetails:Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        internal static string VacancyDetails_month_s_ {
            get {
                return ResourceManager.GetString("VacancyDetails:month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opportunities.
        /// </summary>
        internal static string VacancyDetails_opportunities {
            get {
                return ResourceManager.GetString("VacancyDetails:opportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        internal static string VacancyDetails_Posted {
            get {
                return ResourceManager.GetString("VacancyDetails:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required year of experience.
        /// </summary>
        internal static string VacancyDetails_Required_year_of_experience {
            get {
                return ResourceManager.GetString("VacancyDetails:Required year of experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string VacancyDetails_Sign_In {
            get {
                return ResourceManager.GetString("VacancyDetails:Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string VacancyDetails_Sign_Up {
            get {
                return ResourceManager.GetString("VacancyDetails:Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, the deadline has already expired.
        /// </summary>
        internal static string VacancyDetails_Unfortunately__the_deadline_has_already_expired {
            get {
                return ResourceManager.GetString("VacancyDetails:Unfortunately, the deadline has already expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a cover letter, answer few questions and send your application!.
        /// </summary>
        internal static string VacancyDetails_Write_a_cover_letter__answer_few_questions_and_send_your_application_ {
            get {
                return ResourceManager.GetString("VacancyDetails:Write a cover letter, answer few questions and send your applicati" +
                        "on!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year(s).
        /// </summary>
        internal static string VacancyDetails_year_s_ {
            get {
                return ResourceManager.GetString("VacancyDetails:year(s)", resourceCulture);
            }
        }
    }
}
