//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRA.Jobs.Client.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRA.Jobs.Client.Resources.Languages.Russian", typeof(Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Applicateons_Add {
            get {
                return ResourceManager.GetString("Applicateons:Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить заметку.
        /// </summary>
        internal static string Applicateons_AddNote {
            get {
                return ResourceManager.GetString("Applicateons:AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить статус.
        /// </summary>
        internal static string Applicateons_Changestatus {
            get {
                return ResourceManager.GetString("Applicateons:Changestatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтры.
        /// </summary>
        internal static string Applicateons_Filters {
            get {
                return ResourceManager.GetString("Applicateons:Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заметки.
        /// </summary>
        internal static string Applicateons_Notes {
            get {
                return ResourceManager.GetString("Applicateons:Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать статус.
        /// </summary>
        internal static string Applicateons_Selectstatus {
            get {
                return ResourceManager.GetString("Applicateons:Selectstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        internal static string Applicateons_Status {
            get {
                return ResourceManager.GetString("Applicateons:Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка успешно отправлена!.
        /// </summary>
        internal static string Application_Success {
            get {
                return ResourceManager.GetString("Application:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кандидаты.
        /// </summary>
        internal static string Candidates {
            get {
                return ResourceManager.GetString("Candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая категория.
        /// </summary>
        internal static string Category_NewCategory {
            get {
                return ResourceManager.GetString("Category:NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to час назад.
        /// </summary>
        internal static string ConverterService_HourAgo {
            get {
                return ResourceManager.GetString("ConverterService:HourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to час остался.
        /// </summary>
        internal static string ConverterService_HourLeft {
            get {
                return ResourceManager.GetString("ConverterService:HourLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to час(а)(ов) назад.
        /// </summary>
        internal static string ConverterService_HoursAgo {
            get {
                return ResourceManager.GetString("ConverterService:HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to час(а)(ов) осталось.
        /// </summary>
        internal static string ConverterService_HoursLeft {
            get {
                return ResourceManager.GetString("ConverterService:HoursLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to минут(у) назад.
        /// </summary>
        internal static string ConverterService_MinAgo {
            get {
                return ResourceManager.GetString("ConverterService:MinAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to минут осталось.
        /// </summary>
        internal static string ConverterService_MinLeft {
            get {
                return ResourceManager.GetString("ConverterService:MinLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в.
        /// </summary>
        internal static string ConverterService_On {
            get {
                return ResourceManager.GetString("ConverterService:On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to секунд(ы) назад.
        /// </summary>
        internal static string ConverterService_SecondsAgo {
            get {
                return ResourceManager.GetString("ConverterService:SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to секунд осталось.
        /// </summary>
        internal static string ConverterService_SecondsLeft {
            get {
                return ResourceManager.GetString("ConverterService:SecondsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня в.
        /// </summary>
        internal static string ConverterService_TodayAt {
            get {
                return ResourceManager.GetString("ConverterService:TodayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завтра.
        /// </summary>
        internal static string ConverterService_Tomorrow {
            get {
                return ResourceManager.GetString("ConverterService:Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчера.
        /// </summary>
        internal static string ConverterService_Yesterday {
            get {
                return ResourceManager.GetString("ConverterService:Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        internal static string Dashboard_Appilcations_Action {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя заявителя.
        /// </summary>
        internal static string Dashboard_Appilcations_Applicant_username {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applicant username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подано в.
        /// </summary>
        internal static string Dashboard_Appilcations_Applied_at {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applied at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать резюме кандидата.
        /// </summary>
        internal static string Dashboard_Appilcations_More_CVButton {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:More:CVButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование статуса.
        /// </summary>
        internal static string Dashboard_Appilcations_Status_name {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Status name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок вакансии.
        /// </summary>
        internal static string Dashboard_Appilcations_Vacancy_title {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Vacancy title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка добавления, возможно, вы ввели дублирующую роль..
        /// </summary>
        internal static string DuplicateRole {
            get {
                return ResourceManager.GetString("DuplicateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаление.
        /// </summary>
        internal static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация Google не удалась. Пожалуйста, повторите попытку позже..
        /// </summary>
        internal static string GoogleAuthFailed {
            get {
                return ResourceManager.GetString("GoogleAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Академия.
        /// </summary>
        internal static string Header_Academy {
            get {
                return ResourceManager.GetString("Header:Academy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        internal static string Header_Category {
            get {
                return ResourceManager.GetString("Header:Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        internal static string Header_Home {
            get {
                return ResourceManager.GetString("Header:Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стажировки.
        /// </summary>
        internal static string Header_Internships {
            get {
                return ResourceManager.GetString("Header:Internships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансии.
        /// </summary>
        internal static string Header_Jobs {
            get {
                return ResourceManager.GetString("Header:Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить email.
        /// </summary>
        internal static string Header_SendEmail {
            get {
                return ResourceManager.GetString("Header:SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить sms.
        /// </summary>
        internal static string Header_SendMessage {
            get {
                return ResourceManager.GetString("Header:SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда.
        /// </summary>
        internal static string Header_Team {
            get {
                return ResourceManager.GetString("Header:Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренинги.
        /// </summary>
        internal static string Header_Trainings {
            get {
                return ResourceManager.GetString("Header:Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер пользователей.
        /// </summary>
        internal static string Header_Usersmanager {
            get {
                return ResourceManager.GetString("Header:Usersmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О.
        /// </summary>
        internal static string Home_About {
            get {
                return ResourceManager.GetString("Home:About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Профессионалы Шелкового пути (SRP) - это компания, занимающаяся разработкой программного обеспечения полного цикла, основанная в 2014 году..
        /// </summary>
        internal static string Home_AboutContent {
            get {
                return ResourceManager.GetString("Home:AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессионалы Шелкового пути.
        /// </summary>
        internal static string Home_AboutTitle {
            get {
                return ResourceManager.GetString("Home:AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        internal static string Home_Address {
            get {
                return ResourceManager.GetString("Home:Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согд, район Джаббор Расулов,.
        /// </summary>
        internal static string Home_Address_p1 {
            get {
                return ResourceManager.GetString("Home:Address_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дехмой, улица Сомони 80.
        /// </summary>
        internal static string Home_Address_p2 {
            get {
                return ResourceManager.GetString("Home:Address_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гибкость.
        /// </summary>
        internal static string Home_Agile {
            get {
                return ResourceManager.GetString("Home:Agile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наш главный приоритет - удовлетворение потребностей клиента путем ранней и непрерывной поставки ценного програмного обеспечения..
        /// </summary>
        internal static string Home_AgileDetails {
            get {
                return ResourceManager.GetString("Home:AgileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения.
        /// </summary>
        internal static string Home_Apps {
            get {
                return ResourceManager.GetString("Home:Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создавайте удивительное.
        /// </summary>
        internal static string Home_BuildAmazing {
            get {
                return ResourceManager.GetString("Home:BuildAmazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всегда в поисках передовых технологий. Создавайте не только продукт, который хорошо продается, но и платформу для его доставки..
        /// </summary>
        internal static string Home_BuildAmazing_Content_ {
            get {
                return ResourceManager.GetString("Home:BuildAmazing_Content.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент.
        /// </summary>
        internal static string Home_Client {
            get {
                return ResourceManager.GetString("Home:Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мы создаем и запускаем масштабируемые приложения с использованием облачных вычислений..
        /// </summary>
        internal static string Home_CloudServiceDescription {
            get {
                return ResourceManager.GetString("Home:CloudServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработка облачных приложений.
        /// </summary>
        internal static string Home_CloudServiceTitle {
            get {
                return ResourceManager.GetString("Home:CloudServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Качество кода.
        /// </summary>
        internal static string Home_CodeQuality {
            get {
                return ResourceManager.GetString("Home:CodeQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы делаем все возможное, чтобы писать экономичный, поддерживаемый, описательный, тестируемый код..
        /// </summary>
        internal static string Home_CodeQualityDetails {
            get {
                return ResourceManager.GetString("Home:CodeQualityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши контакты.
        /// </summary>
        internal static string Home_Contact {
            get {
                return ResourceManager.GetString("Home:Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постоянное обучение.
        /// </summary>
        internal static string Home_ContinualLearning {
            get {
                return ResourceManager.GetString("Home:ContinualLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы стремимся поддерживать наши навыки и знания на современном уровне, чтобы мы могли удовлетворять требования наших клиентов..
        /// </summary>
        internal static string Home_ContinualLearningDetails {
            get {
                return ResourceManager.GetString("Home:ContinualLearningDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайн.
        /// </summary>
        internal static string Home_Design {
            get {
                return ResourceManager.GetString("Home:Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мы создаем приложения для ОС по вашему выбору..
        /// </summary>
        internal static string Home_DesktopServiceDescription {
            get {
                return ResourceManager.GetString("Home:DesktopServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настольные приложения.
        /// </summary>
        internal static string Home_DesktopServiceTitle {
            get {
                return ResourceManager.GetString("Home:DesktopServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработка.
        /// </summary>
        internal static string Home_Development {
            get {
                return ResourceManager.GetString("Home:Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите нам.
        /// </summary>
        internal static string Home_Email {
            get {
                return ResourceManager.GetString("Home:Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@silkroadprofessionals.com.
        /// </summary>
        internal static string Home_EmailLink {
            get {
                return ResourceManager.GetString("Home:EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы разрабатываем программное обеспечение и предоставляем поддержку программирования в аутсорсинге..
        /// </summary>
        internal static string Home_Hero_Content {
            get {
                return ResourceManager.GetString("Home:Hero_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы здесь.
        /// </summary>
        internal static string Home_Hero_Title_1 {
            get {
                return ResourceManager.GetString("Home:Hero_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Чтобы помочь вам!.
        /// </summary>
        internal static string Home_Hero_Title_2 {
            get {
                return ResourceManager.GetString("Home:Hero_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как.
        /// </summary>
        internal static string Home_How {
            get {
                return ResourceManager.GetString("Home:How", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренний контроль.
        /// </summary>
        internal static string Home_IntrinsicControl {
            get {
                return ResourceManager.GetString("Home:IntrinsicControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы поощряем наших программистов быть самомотивированными в улучшении своих навыков и производстве высококачественной работы..
        /// </summary>
        internal static string Home_IntrinsicControlDetails {
            get {
                return ResourceManager.GetString("Home:IntrinsicControlDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Встречайте.
        /// </summary>
        internal static string Home_Meet {
            get {
                return ResourceManager.GetString("Home:Meet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привлечь в команду местных талантливых IT-специалистов и дать им возможность оказывать выдающиеся IT-услуги нашим партнерам.
        /// </summary>
        internal static string Home_MissionContent {
            get {
                return ResourceManager.GetString("Home:MissionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАША МИССИЯ.
        /// </summary>
        internal static string Home_MissionTitle {
            get {
                return ResourceManager.GetString("Home:MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы создаем нативные и кросс-платформенные мобильные приложения..
        /// </summary>
        internal static string Home_MobileServiceDescription {
            get {
                return ResourceManager.GetString("Home:MobileServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильная разработка.
        /// </summary>
        internal static string Home_MobileServiceTitle {
            get {
                return ResourceManager.GetString("Home:MobileServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Наша команда.
        /// </summary>
        internal static string Home_OurTeam {
            get {
                return ResourceManager.GetString("Home:OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отзывы партнеров.
        /// </summary>
        internal static string Home_Partner {
            get {
                return ResourceManager.GetString("Home:Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирование.
        /// </summary>
        internal static string Home_Planning {
            get {
                return ResourceManager.GetString("Home:Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные принципы.
        /// </summary>
        internal static string Home_Principles {
            get {
                return ResourceManager.GetString("Home:Principles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продуктивность.
        /// </summary>
        internal static string Home_Productivity {
            get {
                return ResourceManager.GetString("Home:Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы стремимся предоставить инструменты и среду, необходимые нашим программистам для достижения максимальной продуктивности..
        /// </summary>
        internal static string Home_ProductivityDetails {
            get {
                return ResourceManager.GetString("Home:ProductivityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Нас.
        /// </summary>
        internal static string Home_Us {
            get {
                return ResourceManager.GetString("Home:Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть команду.
        /// </summary>
        internal static string Home_ViewTeam {
            get {
                return ResourceManager.GetString("Home:ViewTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поднять наших бизнес-партнеров на новый уровень успеха, предоставляя замечательные услуги по аутсорсингу и аутстаффингу в области IT.
        /// </summary>
        internal static string Home_VisionContent {
            get {
                return ResourceManager.GetString("Home:VisionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАШЕ ВИДЕНИЕ.
        /// </summary>
        internal static string Home_VisionTitle {
            get {
                return ResourceManager.GetString("Home:VisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы разрабатываем веб-сайты и корпоративные веб-приложения..
        /// </summary>
        internal static string Home_WebServiceDescription {
            get {
                return ResourceManager.GetString("Home:WebServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработка веб-сайтов.
        /// </summary>
        internal static string Home_WebServiceTitle {
            get {
                return ResourceManager.GetString("Home:WebServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мы делаем.
        /// </summary>
        internal static string Home_WeDo {
            get {
                return ResourceManager.GetString("Home:WeDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мы работаем.
        /// </summary>
        internal static string Home_WeWork {
            get {
                return ResourceManager.GetString("Home:WeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что.
        /// </summary>
        internal static string Home_What {
            get {
                return ResourceManager.GetString("Home:What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часы работы.
        /// </summary>
        internal static string Home_WorkingHours {
            get {
                return ResourceManager.GetString("Home:WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пн: с 12:00 до 21:00.
        /// </summary>
        internal static string Home_WorkingHours1 {
            get {
                return ResourceManager.GetString("Home:WorkingHours1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вт - Пт: с 8:00 до 17:30.
        /// </summary>
        internal static string Home_WorkingHours2 {
            get {
                return ResourceManager.GetString("Home:WorkingHours2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сб - Вс: закрыто.
        /// </summary>
        internal static string Home_WorkingHours3 {
            get {
                return ResourceManager.GetString("Home:WorkingHours3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить вопрос.
        /// </summary>
        internal static string Internships_AddQuestion {
            get {
                return ResourceManager.GetString("Internships:AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить задачу.
        /// </summary>
        internal static string Internships_AddTask {
            get {
                return ResourceManager.GetString("Internships:AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайний срок подачи заявок.
        /// </summary>
        internal static string Internships_ApplicationDeadline {
            get {
                return ResourceManager.GetString("Internships:ApplicationDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string Internships_Create {
            get {
                return ResourceManager.GetString("Internships:Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую вакансию для стажировки.
        /// </summary>
        internal static string Internships_CreateInternship {
            get {
                return ResourceManager.GetString("Internships:CreateInternship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string Internships_Date {
            get {
                return ResourceManager.GetString("Internships:Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить изображение.
        /// </summary>
        internal static string Internships_InsertImage {
            get {
                return ResourceManager.GetString("Internships:InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стажировки.
        /// </summary>
        internal static string Internships_Internships {
            get {
                return ResourceManager.GetString("Internships:Internships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансии стажировок.
        /// </summary>
        internal static string Internships_InternshipsVacancy {
            get {
                return ResourceManager.GetString("Internships:InternshipsVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая вакансия для стажировки.
        /// </summary>
        internal static string Internships_NewInternship {
            get {
                return ResourceManager.GetString("Internships:NewInternship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата публикации.
        /// </summary>
        internal static string Internships_PublishDate {
            get {
                return ResourceManager.GetString("Internships:PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Internships_Remove {
            get {
                return ResourceManager.GetString("Internships:Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск вакансий.
        /// </summary>
        internal static string Internships_Searchjobs {
            get {
                return ResourceManager.GetString("Internships:Searchjobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое описание.
        /// </summary>
        internal static string Internships_ShortDescription {
            get {
                return ResourceManager.GetString("Internships:ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стипендия.
        /// </summary>
        internal static string Internships_Stipend {
            get {
                return ResourceManager.GetString("Internships:Stipend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        internal static string Internships_Tasks {
            get {
                return ResourceManager.GetString("Internships:Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон.
        /// </summary>
        internal static string Internships_Template {
            get {
                return ResourceManager.GetString("Internships:Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест.
        /// </summary>
        internal static string Internships_Test {
            get {
                return ResourceManager.GetString("Internships:Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        internal static string Internships_Time {
            get {
                return ResourceManager.GetString("Internships:Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        internal static string Internships_Title {
            get {
                return ResourceManager.GetString("Internships:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы к вакансии.
        /// </summary>
        internal static string Internships_Vacancyquestions {
            get {
                return ResourceManager.GetString("Internships:Vacancyquestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую вакансию для работы.
        /// </summary>
        internal static string job_CreateNewJob {
            get {
                return ResourceManager.GetString("job:CreateNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая вакансия для работы.
        /// </summary>
        internal static string job_NewVacancy {
            get {
                return ResourceManager.GetString("job:NewVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимый опыт работы (в годах).
        /// </summary>
        internal static string job_Requiredyear {
            get {
                return ResourceManager.GetString("job:Requiredyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать категорию.
        /// </summary>
        internal static string job_Selectcategory {
            get {
                return ResourceManager.GetString("job:Selectcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График работы.
        /// </summary>
        internal static string job_WorkSchedule {
            get {
                return ResourceManager.GetString("job:WorkSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансии.
        /// </summary>
        internal static string Jobs_Jobs {
            get {
                return ResourceManager.GetString("Jobs:Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string Per_Page {
            get {
                return ResourceManager.GetString("Per Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О себе.
        /// </summary>
        internal static string Profile_AboutMyself {
            get {
                return ResourceManager.GetString("Profile:AboutMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новое образование.
        /// </summary>
        internal static string Profile_AddNewEducation {
            get {
                return ResourceManager.GetString("Profile:AddNewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новый опыт.
        /// </summary>
        internal static string Profile_AddNewExperience {
            get {
                return ResourceManager.GetString("Profile:AddNewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить навык.
        /// </summary>
        internal static string Profile_AddSkill {
            get {
                return ResourceManager.GetString("Profile:AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Profile_Cancel {
            get {
                return ResourceManager.GetString("Profile:Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код отправлен.
        /// </summary>
        internal static string Profile_Codesent {
            get {
                return ResourceManager.GetString("Profile:Codesent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название компании.
        /// </summary>
        internal static string Profile_CompanyName {
            get {
                return ResourceManager.GetString("Profile:CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        internal static string Profile_Confirm {
            get {
                return ResourceManager.GetString("Profile:Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код подтверждения.
        /// </summary>
        internal static string Profile_Confirmationcode {
            get {
                return ResourceManager.GetString("Profile:Confirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждено.
        /// </summary>
        internal static string Profile_Confirmed {
            get {
                return ResourceManager.GetString("Profile:Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая работа.
        /// </summary>
        internal static string Profile_CurrentJob {
            get {
                return ResourceManager.GetString("Profile:CurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        internal static string Profile_DateOfBirth {
            get {
                return ResourceManager.GetString("Profile:DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string Profile_Description {
            get {
                return ResourceManager.GetString("Profile:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образование.
        /// </summary>
        internal static string Profile_Educations {
            get {
                return ResourceManager.GetString("Profile:Educations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email не подтвержден!.
        /// </summary>
        internal static string Profile_EmailisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:EmailisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опыт работы.
        /// </summary>
        internal static string Profile_Experience {
            get {
                return ResourceManager.GetString("Profile:Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опыт работы.
        /// </summary>
        internal static string Profile_Experiences {
            get {
                return ResourceManager.GetString("Profile:Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Profile_FirstName {
            get {
                return ResourceManager.GetString("Profile:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы хотите выдвинуть себя, отправьте нам свое резюме..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_sendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,sendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы хотите выдвинуть себя, войдите в систему и отправьте нам свое резюме..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_signinandsendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,signinandsendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это текущая работа.
        /// </summary>
        internal static string Profile_IsCurrentJob {
            get {
                return ResourceManager.GetString("Profile:IsCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        internal static string Profile_JobTitle {
            get {
                return ResourceManager.GetString("Profile:JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        internal static string Profile_LastName {
            get {
                return ResourceManager.GetString("Profile:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой профиль.
        /// </summary>
        internal static string Profile_MyProfile {
            get {
                return ResourceManager.GetString("Profile:MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое образование.
        /// </summary>
        internal static string Profile_NewEducation {
            get {
                return ResourceManager.GetString("Profile:NewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый опыт.
        /// </summary>
        internal static string Profile_NewExperience {
            get {
                return ResourceManager.GetString("Profile:NewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        internal static string Profile_OldPassword {
            get {
                return ResourceManager.GetString("Profile:OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личная информация.
        /// </summary>
        internal static string Profile_PersonalInformation {
            get {
                return ResourceManager.GetString("Profile:PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона не подтвержден!.
        /// </summary>
        internal static string Profile_PhoneNumberisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:PhoneNumberisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настоящее время.
        /// </summary>
        internal static string Profile_Present {
            get {
                return ResourceManager.GetString("Profile:Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Profile_Save {
            get {
                return ResourceManager.GetString("Profile:Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения.
        /// </summary>
        internal static string Profile_Savechanges {
            get {
                return ResourceManager.GetString("Profile:Savechanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        internal static string Profile_SelectLanguage {
            get {
                return ResourceManager.GetString("Profile:SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер не отвечает.
        /// </summary>
        internal static string Profile_Serverisnotresponding {
            get {
                return ResourceManager.GetString("Profile:Serverisnotresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навыки.
        /// </summary>
        internal static string Profile_Skills {
            get {
                return ResourceManager.GetString("Profile:Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальность.
        /// </summary>
        internal static string Profile_Specialty {
            get {
                return ResourceManager.GetString("Profile:Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала.
        /// </summary>
        internal static string Profile_StartDate {
            get {
                return ResourceManager.GetString("Profile:StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключиться на темную тему.
        /// </summary>
        internal static string Profile_SwitchtoDarkTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключиться на светлую тему.
        /// </summary>
        internal static string Profile_SwitchtoLightTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключиться на систему.
        /// </summary>
        internal static string Profile_Switchtosystem {
            get {
                return ResourceManager.GetString("Profile:Switchtosystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус вашего резюме для вашей кандидатуры.
        /// </summary>
        internal static string Profile_ThestatusofyourCVforyourcandidacyis {
            get {
                return ResourceManager.GetString("Profile:ThestatusofyourCVforyourcandidacyis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы изменить пароль, введите старый пароль, а затем создайте новый, надежный пароль..
        /// </summary>
        internal static string Profile_Tochangeyourpassword_enteryouroldpassword_andthencreateanew_strongpassword_ {
            get {
                return ResourceManager.GetString("Profile:Tochangeyourpassword,enteryouroldpassword,andthencreateanew,strongpasswor" +
                        "d.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте снова.
        /// </summary>
        internal static string Profile_TryAgain {
            get {
                return ResourceManager.GetString("Profile:TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университет.
        /// </summary>
        internal static string Profile_University {
            get {
                return ResourceManager.GetString("Profile:University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До сих пор.
        /// </summary>
        internal static string Profile_UntilNow {
            get {
                return ResourceManager.GetString("Profile:UntilNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string Profile_Update {
            get {
                return ResourceManager.GetString("Profile:Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить резюме.
        /// </summary>
        internal static string Profile_UploadCV {
            get {
                return ResourceManager.GetString("Profile:UploadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить новое резюме.
        /// </summary>
        internal static string Profile_UploadNewCV {
            get {
                return ResourceManager.GetString("Profile:UploadNewCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        internal static string ResetPassword_Changepassword {
            get {
                return ResourceManager.GetString("ResetPassword:Changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        internal static string ResetPassword_NewPassword {
            get {
                return ResourceManager.GetString("ResetPassword:NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        internal static string ResetPassword_PhoneNumber {
            get {
                return ResourceManager.GetString("ResetPassword:PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить код еще раз.
        /// </summary>
        internal static string ResetPassword_Resendcode {
            get {
                return ResourceManager.GetString("ResetPassword:Resendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить код подтверждения.
        /// </summary>
        internal static string ResetPassword_Sendconfirmationcode {
            get {
                return ResourceManager.GetString("ResetPassword:Sendconfirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string SendCV_Close {
            get {
                return ResourceManager.GetString("SendCV:Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше сообщение.
        /// </summary>
        internal static string SendCV_CoverLetter {
            get {
                return ResourceManager.GetString("SendCV:CoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, загрузите свое резюме.
        /// </summary>
        internal static string SendCV_IfFileNull {
            get {
                return ResourceManager.GetString("SendCV:IfFileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте нам ваше резюме.
        /// </summary>
        internal static string SendCV_Title {
            get {
                return ResourceManager.GetString("SendCV:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше имя.
        /// </summary>
        internal static string SendCV_Your_name {
            get {
                return ResourceManager.GetString("SendCV:Your name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш номер телефона.
        /// </summary>
        internal static string SendCV_Your_phone_number {
            get {
                return ResourceManager.GetString("SendCV:Your phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер не отвечает, попробуйте позже.
        /// </summary>
        internal static string ServerIsNotResponding {
            get {
                return ResourceManager.GetString("ServerIsNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет аккаунта?.
        /// </summary>
        internal static string SignIn_LabelDontAccount {
            get {
                return ResourceManager.GetString("SignIn:LabelDontAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        internal static string SignIn_LabelForgot {
            get {
                return ResourceManager.GetString("SignIn:LabelForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Сбросить пароль.
        /// </summary>
        internal static string SignIn_LinkReset {
            get {
                return ResourceManager.GetString("SignIn:LinkReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Зарегистрироваться.
        /// </summary>
        internal static string SignIn_LinkSignUp {
            get {
                return ResourceManager.GetString("SignIn:LinkSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string SignIn_Password {
            get {
                return ResourceManager.GetString("SignIn:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string SignIn_SignIn {
            get {
                return ResourceManager.GetString("SignIn:SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string SignIn_UserName {
            get {
                return ResourceManager.GetString("SignIn:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string SignUp_Apply {
            get {
                return ResourceManager.GetString("SignUp:Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        internal static string SignUp_ButtonNext {
            get {
                return ResourceManager.GetString("SignUp:ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string SignUp_Code {
            get {
                return ResourceManager.GetString("SignUp:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        internal static string SignUp_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        internal static string SignUp_ConfirmPassword_HelperText {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        internal static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp:Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить с.
        /// </summary>
        internal static string SignUp_ExternalLoginCard {
            get {
                return ResourceManager.GetString("SignUp:ExternalLoginCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string SignUp_FirstName {
            get {
                return ResourceManager.GetString("SignUp:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ваше имя.
        /// </summary>
        internal static string SignUp_FirstName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:FirstName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас есть аккаунт?.
        /// </summary>
        internal static string SignUp_LabelHaveAccount {
            get {
                return ResourceManager.GetString("SignUp:LabelHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string SignUp_LabelSignUp {
            get {
                return ResourceManager.GetString("SignUp:LabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        internal static string SignUp_LastName {
            get {
                return ResourceManager.GetString("SignUp:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите вашу фамилию.
        /// </summary>
        internal static string SignUp_LastName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:LastName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Войти.
        /// </summary>
        internal static string SignUp_LinkSignIn {
            get {
                return ResourceManager.GetString("SignUp:LinkSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы отправили код подтверждения на этот номер: $phone$. Пожалуйста, подтвердите свою личность.
        /// </summary>
        internal static string signUp_messageText {
            get {
                return ResourceManager.GetString("signUp:messageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string SignUp_Password_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Password_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string SignUp_Phone {
            get {
                return ResourceManager.GetString("SignUp:Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ваш номер телефона.
        /// </summary>
        internal static string SignUp_Phone_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Phone_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить код повторно.
        /// </summary>
        internal static string SignUp_ResendCode {
            get {
                return ResourceManager.GetString("SignUp:ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to секунд осталось для повторной отправки кода..
        /// </summary>
        internal static string SignUp_Secconds {
            get {
                return ResourceManager.GetString("SignUp:Secconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string SignUp_UserName {
            get {
                return ResourceManager.GetString("SignUp:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так.
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую вакансию для Тренинг.
        /// </summary>
        internal static string Training_NewTraining {
            get {
                return ResourceManager.GetString("Training:NewTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая вакансия для Тренинг.
        /// </summary>
        internal static string Training_NewTrainingV {
            get {
                return ResourceManager.GetString("Training:NewTrainingV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренинги.
        /// </summary>
        internal static string Trainings_Trainings {
            get {
                return ResourceManager.GetString("Trainings:Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклики.
        /// </summary>
        internal static string UserButton_Applications {
            get {
                return ResourceManager.GetString("UserButton:Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string UserButton_Logout {
            get {
                return ResourceManager.GetString("UserButton:Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string UserButton_Profile {
            get {
                return ResourceManager.GetString("UserButton:Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string UserButton_Sign_In {
            get {
                return ResourceManager.GetString("UserButton:Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string UserButton_Sign_Up {
            get {
                return ResourceManager.GetString("UserButton:Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное имя.
        /// </summary>
        internal static string UserManager_FullName {
            get {
                return ResourceManager.GetString("UserManager:FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        internal static string UserManager_Loading {
            get {
                return ResourceManager.GetString("UserManager:Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Совпадающих записей не найдено.
        /// </summary>
        internal static string UserManager_Nomatchingrecords {
            get {
                return ResourceManager.GetString("UserManager:Nomatchingrecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        internal static string UserManager_Roles {
            get {
                return ResourceManager.GetString("UserManager:Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по имени пользователя или полному имени.
        /// </summary>
        internal static string UserManager_Searchname {
            get {
                return ResourceManager.GetString("UserManager:Searchname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string UserManager_Users {
            get {
                return ResourceManager.GetString("UserManager:Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        internal static string UserRoles_Gender {
            get {
                return ResourceManager.GetString("UserRoles:Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        internal static string UserRoles_History {
            get {
                return ResourceManager.GetString("UserRoles:History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личные данные.
        /// </summary>
        internal static string UserRoles_PersonalData {
            get {
                return ResourceManager.GetString("UserRoles:PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не подтверждено.
        /// </summary>
        internal static string UserRoles_UnConfirmed {
            get {
                return ResourceManager.GetString("UserRoles:UnConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string VacanciesList_All {
            get {
                return ResourceManager.GetString("VacanciesList:All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        internal static string VacanciesList_Categories {
            get {
                return ResourceManager.GetString("VacanciesList:Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок.
        /// </summary>
        internal static string VacanciesList_Deadline {
            get {
                return ResourceManager.GetString("VacanciesList:Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность.
        /// </summary>
        internal static string VacanciesList_Duration {
            get {
                return ResourceManager.GetString("VacanciesList:Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата завершения.
        /// </summary>
        internal static string VacanciesList_End_date {
            get {
                return ResourceManager.GetString("VacanciesList:End date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to месяц(ев).
        /// </summary>
        internal static string VacanciesList_month_s_ {
            get {
                return ResourceManager.GetString("VacanciesList:month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На данный момент нет доступных вакансий. Пожалуйста, проверьте позже :).
        /// </summary>
        internal static string VacanciesList_NoJobs {
            get {
                return ResourceManager.GetString("VacanciesList:NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовано.
        /// </summary>
        internal static string VacanciesList_Posted {
            get {
                return ResourceManager.GetString("VacanciesList:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        internal static string VacanciesList_Search {
            get {
                return ResourceManager.GetString("VacanciesList:Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные детали.
        /// </summary>
        internal static string VacancyApplication_Additional_Details {
            get {
                return ResourceManager.GetString("VacancyApplication:Additional Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string VacancyApplication_Apply {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить, используя профиль.
        /// </summary>
        internal static string VacancyApplication_Apply_using_profile {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply using profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить, загрузив файл.
        /// </summary>
        internal static string VacancyApplication_Apply_with_uploading_file {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply with uploading file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопроводительное письмо.
        /// </summary>
        internal static string VacancyApplication_Cover_Letter {
            get {
                return ResourceManager.GetString("VacancyApplication:Cover Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок.
        /// </summary>
        internal static string VacancyApplication_Deadline {
            get {
                return ResourceManager.GetString("VacancyApplication:Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность.
        /// </summary>
        internal static string VacancyApplication_Duration {
            get {
                return ResourceManager.GetString("VacancyApplication:Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата завершения.
        /// </summary>
        internal static string VacancyApplication_End_Date {
            get {
                return ResourceManager.GetString("VacancyApplication:End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборы.
        /// </summary>
        internal static string VacancyApplication_Fees {
            get {
                return ResourceManager.GetString("VacancyApplication:Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to месяц(ев).
        /// </summary>
        internal static string VacancyApplication_month_s_ {
            get {
                return ResourceManager.GetString("VacancyApplication:month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовано.
        /// </summary>
        internal static string VacancyApplication_Posted {
            get {
                return ResourceManager.GetString("VacancyApplication:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка.
        /// </summary>
        internal static string VacancyApplication_Processing {
            get {
                return ResourceManager.GetString("VacancyApplication:Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы.
        /// </summary>
        internal static string VacancyApplication_Questions {
            get {
                return ResourceManager.GetString("VacancyApplication:Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуемый опыт работы в годах.
        /// </summary>
        internal static string VacancyApplication_Required_year_of_experience {
            get {
                return ResourceManager.GetString("VacancyApplication:Required year of experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны дать ответы на необходимые вопросы.
        /// </summary>
        internal static string VacancyApplication_RequiredQuestionHaventAnswer {
            get {
                return ResourceManager.GetString("VacancyApplication:RequiredQuestionHaventAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить свое резюме.
        /// </summary>
        internal static string VacancyApplication_Upload_your_CV {
            get {
                return ResourceManager.GetString("VacancyApplication:Upload your CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали вакансии.
        /// </summary>
        internal static string VacancyApplication_Vacancy_Details {
            get {
                return ResourceManager.GetString("VacancyApplication:Vacancy Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to год(ы).
        /// </summary>
        internal static string VacancyApplication_year_s_ {
            get {
                return ResourceManager.GetString("VacancyApplication:year(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже есть аккаунт?.
        /// </summary>
        internal static string VacancyDetails_Already_have_an_account_ {
            get {
                return ResourceManager.GetString("VacancyDetails:Already have an account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подать заявку сейчас.
        /// </summary>
        internal static string VacancyDetails_Apply_Now {
            get {
                return ResourceManager.GetString("VacancyDetails:Apply Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готовы взять свою карьеру на следующий уровень с.
        /// </summary>
        internal static string VacancyDetails_Are_you_ready_to_take_your_career_to_the_next_level_with {
            get {
                return ResourceManager.GetString("VacancyDetails:Are you ready to take your career to the next level with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок.
        /// </summary>
        internal static string VacancyDetails_Deadline {
            get {
                return ResourceManager.GetString("VacancyDetails:Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать резюме.
        /// </summary>
        internal static string VacancyDetails_Download_CV {
            get {
                return ResourceManager.GetString("VacancyDetails:Download CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность.
        /// </summary>
        internal static string VacancyDetails_Duration {
            get {
                return ResourceManager.GetString("VacancyDetails:Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата завершения.
        /// </summary>
        internal static string VacancyDetails_End_Date {
            get {
                return ResourceManager.GetString("VacancyDetails:End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исследовать.
        /// </summary>
        internal static string VacancyDetails_Explore {
            get {
                return ResourceManager.GetString("VacancyDetails:Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборы.
        /// </summary>
        internal static string VacancyDetails_Fees {
            get {
                return ResourceManager.GetString("VacancyDetails:Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to месяц(ев).
        /// </summary>
        internal static string VacancyDetails_month_s_ {
            get {
                return ResourceManager.GetString("VacancyDetails:month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to возможности.
        /// </summary>
        internal static string VacancyDetails_opportunities {
            get {
                return ResourceManager.GetString("VacancyDetails:opportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовано.
        /// </summary>
        internal static string VacancyDetails_Posted {
            get {
                return ResourceManager.GetString("VacancyDetails:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуемый опыт работы в годах.
        /// </summary>
        internal static string VacancyDetails_Required_year_of_experience {
            get {
                return ResourceManager.GetString("VacancyDetails:Required year of experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string VacancyDetails_Sign_In {
            get {
                return ResourceManager.GetString("VacancyDetails:Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string VacancyDetails_Sign_Up {
            get {
                return ResourceManager.GetString("VacancyDetails:Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, срок подачи заявок уже истек.
        /// </summary>
        internal static string VacancyDetails_Unfortunately__the_deadline_has_already_expired {
            get {
                return ResourceManager.GetString("VacancyDetails:Unfortunately, the deadline has already expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите сопроводительное письмо, ответьте на несколько вопросов и отправьте свою заявку!.
        /// </summary>
        internal static string VacancyDetails_Write_a_cover_letter__answer_few_questions_and_send_your_application_ {
            get {
                return ResourceManager.GetString("VacancyDetails:Write a cover letter, answer few questions and send your applicati" +
                        "on!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to год(ы).
        /// </summary>
        internal static string VacancyDetails_year_s_ {
            get {
                return ResourceManager.GetString("VacancyDetails:year(s)", resourceCulture);
            }
        }
    }
}
