//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRA.Jobs.Client.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tajik {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tajik() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRA.Jobs.Client.Resources.Languages.Tajik", typeof(Tajik).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV-и довталабро зеркашӣ кунед.
        /// </summary>
        internal static string Dashboard_Appilcations_More_CVButton {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:More:CVButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Академия.
        /// </summary>
        internal static string Header_Academy {
            get {
                return ResourceManager.GetString("Header:Academy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Асосӣ.
        /// </summary>
        internal static string Header_Home {
            get {
                return ResourceManager.GetString("Header:Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таҷрибаомӯзӣ.
        /// </summary>
        internal static string Header_Internships {
            get {
                return ResourceManager.GetString("Header:Internships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҷойҳои корӣ.
        /// </summary>
        internal static string Header_Jobs {
            get {
                return ResourceManager.GetString("Header:Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тим.
        /// </summary>
        internal static string Header_Team {
            get {
                return ResourceManager.GetString("Header:Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренингҳо.
        /// </summary>
        internal static string Header_Trainings {
            get {
                return ResourceManager.GetString("Header:Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дар бораи.
        /// </summary>
        internal static string Home_About {
            get {
                return ResourceManager.GetString("Home:About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мутахассисони Роҳи Абрешим (SRP) - ин ширкати тавсияи нармафзори давраи пурра аст, ки дар соли 2014 тасис ёфтааст. Мо дар Вирджиния, ИМА ва Дехмой, Тоҷикистон қонунӣ сабт шудаанд..
        /// </summary>
        internal static string Home_AboutContent {
            get {
                return ResourceManager.GetString("Home:AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мутахассисони Роҳи Абрешим.
        /// </summary>
        internal static string Home_AboutTitle {
            get {
                return ResourceManager.GetString("Home:AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суроға.
        /// </summary>
        internal static string Home_Address {
            get {
                return ResourceManager.GetString("Home:Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суғд, ноҳияи Ҷаббор Расулов, .
        /// </summary>
        internal static string Home_Address_p1 {
            get {
                return ResourceManager.GetString("Home:Address_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деҳмой, кӯчаи Сомонӣ 80.
        /// </summary>
        internal static string Home_Address_p2 {
            get {
                return ResourceManager.GetString("Home:Address_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фасеҳ.
        /// </summary>
        internal static string Home_Agile {
            get {
                return ResourceManager.GetString("Home:Agile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Афзалияти мо қонеъ гардонидани ниёзҳои муштарӣ тавассути интиқоли барвақт ва пайвастаи нармафзори арзишманд мебошад..
        /// </summary>
        internal static string Home_AgileDetails {
            get {
                return ResourceManager.GetString("Home:AgileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Барномаҳо.
        /// </summary>
        internal static string Home_Apps {
            get {
                return ResourceManager.GetString("Home:Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохтаи шгаванд.
        /// </summary>
        internal static string Home_BuildAmazing {
            get {
                return ResourceManager.GetString("Home:BuildAmazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳамеша дар ҷустуҷӯи пешрафтҳои технологии боланд. Танҳо маҳсулотеро сохтан, ки хуб фурӯхт мешавад, балки платформаро, ки тавассути он метавон онро тақсим кард..
        /// </summary>
        internal static string Home_BuildAmazing_Content_ {
            get {
                return ResourceManager.GetString("Home:BuildAmazing_Content.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мизоҷ.
        /// </summary>
        internal static string Home_Client {
            get {
                return ResourceManager.GetString("Home:Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мо бо истифода аз роёниши абрӣ барномаҳои миқёспазир эҷод ва иҷро мекунем..
        /// </summary>
        internal static string Home_CloudServiceDescription {
            get {
                return ResourceManager.GetString("Home:CloudServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рушди абрӣ.
        /// </summary>
        internal static string Home_CloudServiceTitle {
            get {
                return ResourceManager.GetString("Home:CloudServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сифати код.
        /// </summary>
        internal static string Home_CodeQuality {
            get {
                return ResourceManager.GetString("Home:CodeQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мо тамоми кори аз дастамон меомадаро мекунем, то рамзи тавсифӣ, нигоҳдорӣ, камхарҷ ва озмоишшаванда нависем..
        /// </summary>
        internal static string Home_CodeQualityDetails {
            get {
                return ResourceManager.GetString("Home:CodeQualityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тамос.
        /// </summary>
        internal static string Home_Contact {
            get {
                return ResourceManager.GetString("Home:Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Омӯзиши пайваста.
        /// </summary>
        internal static string Home_ContinualLearning {
            get {
                return ResourceManager.GetString("Home:ContinualLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мо мекӯшем, ки малака ва дониши худро навсозӣ кунем, то ба талаботи мизоҷони худ қонеъ гардонем..
        /// </summary>
        internal static string Home_ContinualLearningDetails {
            get {
                return ResourceManager.GetString("Home:ContinualLearningDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарроҳӣ.
        /// </summary>
        internal static string Home_Design {
            get {
                return ResourceManager.GetString("Home:Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мо барои OS интихобкардаи шумо замимаҳо эҷод мекунем..
        /// </summary>
        internal static string Home_DesktopServiceDescription {
            get {
                return ResourceManager.GetString("Home:DesktopServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иловаҳои дасткорӣ.
        /// </summary>
        internal static string Home_DesktopServiceTitle {
            get {
                return ResourceManager.GetString("Home:DesktopServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рушд.
        /// </summary>
        internal static string Home_Development {
            get {
                return ResourceManager.GetString("Home:Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ба мо нависед.
        /// </summary>
        internal static string Home_Email {
            get {
                return ResourceManager.GetString("Home:Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@silkroadprofessionals.com.
        /// </summary>
        internal static string Home_EmailLink {
            get {
                return ResourceManager.GetString("Home:EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боварӣ ба Худо.
        /// </summary>
        internal static string Home_GlorifyGod {
            get {
                return ResourceManager.GetString("Home:GlorifyGod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мо мехоҳем, ки ҳар коре, ки мо мекунем, Худоро ҷалол диҳад..
        /// </summary>
        internal static string Home_GlorifyGodDetails {
            get {
                return ResourceManager.GetString("Home:GlorifyGodDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мо нармафзорро тавсия мекунем ва дастгирии барномасозиро фароҳам мекунем..
        /// </summary>
        internal static string Home_Hero_Content {
            get {
                return ResourceManager.GetString("Home:Hero_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мо дар инҷо ҳастем..
        /// </summary>
        internal static string Home_Hero_Title_1 {
            get {
                return ResourceManager.GetString("Home:Hero_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Барои кӯмак ба шумо!.
        /// </summary>
        internal static string Home_Hero_Title_2 {
            get {
                return ResourceManager.GetString("Home:Hero_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чӣ тавр.
        /// </summary>
        internal static string Home_How {
            get {
                return ResourceManager.GetString("Home:How", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назорати дохилӣ.
        /// </summary>
        internal static string Home_IntrinsicControl {
            get {
                return ResourceManager.GetString("Home:IntrinsicControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мо барномасозони худро ташвиқ мекунем, ки барои такмил додани малакаи худ ва истеҳсоли кори босифат худдорӣ кунанд..
        /// </summary>
        internal static string Home_IntrinsicControlDetails {
            get {
                return ResourceManager.GetString("Home:IntrinsicControlDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шинос шавед.
        /// </summary>
        internal static string Home_Meet {
            get {
                return ResourceManager.GetString("Home:Meet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ба ҷамъияти маҳаллии мутахассисони IT-и дараи истиъдод дастгирӣ кардан, ки ба шарикони мо хидматҳои барҷастаи IT пешниҳод кунанд.
        /// </summary>
        internal static string Home_MissionContent {
            get {
                return ResourceManager.GetString("Home:MissionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МАҚСАДИ МО.
        /// </summary>
        internal static string Home_MissionTitle {
            get {
                return ResourceManager.GetString("Home:MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мо иловаҳои мобилӣ ва кросс-платформа эҷод мекунем..
        /// </summary>
        internal static string Home_MobileServiceDescription {
            get {
                return ResourceManager.GetString("Home:MobileServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рушди мобилӣ.
        /// </summary>
        internal static string Home_MobileServiceTitle {
            get {
                return ResourceManager.GetString("Home:MobileServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Тими мо.
        /// </summary>
        internal static string Home_OurTeam {
            get {
                return ResourceManager.GetString("Home:OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ва баррасиҳои шарикон.
        /// </summary>
        internal static string Home_Partner {
            get {
                return ResourceManager.GetString("Home:Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Барномарезӣ.
        /// </summary>
        internal static string Home_Planning {
            get {
                return ResourceManager.GetString("Home:Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принсипҳои асосӣ.
        /// </summary>
        internal static string Home_Principles {
            get {
                return ResourceManager.GetString("Home:Principles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маҳсулнокӣ.
        /// </summary>
        internal static string Home_Productivity {
            get {
                return ResourceManager.GetString("Home:Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мо мекӯшем, ки асбобҳо ва муҳити атрофро фароҳам орем, ки барномасозони мо бояд то ҳадди имкон самаранок бошанд..
        /// </summary>
        internal static string Home_ProductivityDetails {
            get {
                return ResourceManager.GetString("Home:ProductivityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мо.
        /// </summary>
        internal static string Home_Us {
            get {
                return ResourceManager.GetString("Home:Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дидани Тим.
        /// </summary>
        internal static string Home_ViewTeam {
            get {
                return ResourceManager.GetString("Home:ViewTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шарикони тиҷоратии моро тавассути пешниҳоди хидматҳои барҷастаи аутсорсинги IT ва аутстаффинг ба сатҳҳои нави муваффақият расонидан.
        /// </summary>
        internal static string Home_VisionContent {
            get {
                return ResourceManager.GetString("Home:VisionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДИДБИНИИ МО.
        /// </summary>
        internal static string Home_VisionTitle {
            get {
                return ResourceManager.GetString("Home:VisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мо веб-сайтҳо ва иловаҳои веб-корпоратсияро тавсия мекунем..
        /// </summary>
        internal static string Home_WebServiceDescription {
            get {
                return ResourceManager.GetString("Home:WebServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рушди веб.
        /// </summary>
        internal static string Home_WebServiceTitle {
            get {
                return ResourceManager.GetString("Home:WebServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  чӣ мекунем.
        /// </summary>
        internal static string Home_WeDo {
            get {
                return ResourceManager.GetString("Home:WeDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Мо кор мекунем.
        /// </summary>
        internal static string Home_WeWork {
            get {
                return ResourceManager.GetString("Home:WeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мо.
        /// </summary>
        internal static string Home_What {
            get {
                return ResourceManager.GetString("Home:What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соатҳои корӣ.
        /// </summary>
        internal static string Home_WorkingHours {
            get {
                return ResourceManager.GetString("Home:WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Душанбе: аз 12:00 то 21:00.
        /// </summary>
        internal static string Home_WorkingHours1 {
            get {
                return ResourceManager.GetString("Home:WorkingHours1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сушанбе - Ҷумъа: аз 8:00 то 17:30.
        /// </summary>
        internal static string Home_WorkingHours2 {
            get {
                return ResourceManager.GetString("Home:WorkingHours2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шанбе - Якшанбе: истироҳат.
        /// </summary>
        internal static string Home_WorkingHours3 {
            get {
                return ResourceManager.GetString("Home:WorkingHours3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тачрибаомузихо.
        /// </summary>
        internal static string Internships_Internships {
            get {
                return ResourceManager.GetString("Internships:Internships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҷойҳои холии корӣ.
        /// </summary>
        internal static string Jobs_Jobs {
            get {
                return ResourceManager.GetString("Jobs:Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дар бораи худ.
        /// </summary>
        internal static string Profile_AboutMyself {
            get {
                return ResourceManager.GetString("Profile:AboutMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таълими нав илова кунед.
        /// </summary>
        internal static string Profile_AddNewEducation {
            get {
                return ResourceManager.GetString("Profile:AddNewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таҷрибаи нав илова кунед.
        /// </summary>
        internal static string Profile_AddNewExperience {
            get {
                return ResourceManager.GetString("Profile:AddNewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маҳорат илова кунед.
        /// </summary>
        internal static string Profile_AddSkill {
            get {
                return ResourceManager.GetString("Profile:AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бекор кунед.
        /// </summary>
        internal static string Profile_Cancel {
            get {
                return ResourceManager.GetString("Profile:Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код фиристода шуд.
        /// </summary>
        internal static string Profile_Codesent {
            get {
                return ResourceManager.GetString("Profile:Codesent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи ширкат.
        /// </summary>
        internal static string Profile_CompanyName {
            get {
                return ResourceManager.GetString("Profile:CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тасдиқ кунед.
        /// </summary>
        internal static string Profile_Confirm {
            get {
                return ResourceManager.GetString("Profile:Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коди тасдиқ.
        /// </summary>
        internal static string Profile_Confirmationcode {
            get {
                return ResourceManager.GetString("Profile:Confirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тасдиқ шуд.
        /// </summary>
        internal static string Profile_Confirmed {
            get {
                return ResourceManager.GetString("Profile:Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кори ҷорӣ.
        /// </summary>
        internal static string Profile_CurrentJob {
            get {
                return ResourceManager.GetString("Profile:CurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Санаи таваллуд.
        /// </summary>
        internal static string Profile_DateOfBirth {
            get {
                return ResourceManager.GetString("Profile:DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тавсиф.
        /// </summary>
        internal static string Profile_Description {
            get {
                return ResourceManager.GetString("Profile:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таълим.
        /// </summary>
        internal static string Profile_Educations {
            get {
                return ResourceManager.GetString("Profile:Educations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл тасдиқ нашудааст!.
        /// </summary>
        internal static string Profile_EmailisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:EmailisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таҷриба.
        /// </summary>
        internal static string Profile_Experience {
            get {
                return ResourceManager.GetString("Profile:Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таҷриба.
        /// </summary>
        internal static string Profile_Experiences {
            get {
                return ResourceManager.GetString("Profile:Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ном.
        /// </summary>
        internal static string Profile_FirstName {
            get {
                return ResourceManager.GetString("Profile:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агар шумо хоҳед, ки худро номинатсия кунед, ба мо CV-и худро фиристед..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_sendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,sendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агар шумо хоҳед, ки худро номинатсия кунед, вуруд шавед ва ба мо CV-и худро фиристед..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_signinandsendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,signinandsendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ин кори ҷорӣ аст.
        /// </summary>
        internal static string Profile_IsCurrentJob {
            get {
                return ResourceManager.GetString("Profile:IsCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сарвазир.
        /// </summary>
        internal static string Profile_JobTitle {
            get {
                return ResourceManager.GetString("Profile:JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насаб.
        /// </summary>
        internal static string Profile_LastName {
            get {
                return ResourceManager.GetString("Profile:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили ман.
        /// </summary>
        internal static string Profile_MyProfile {
            get {
                return ResourceManager.GetString("Profile:MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таълими нав.
        /// </summary>
        internal static string Profile_NewEducation {
            get {
                return ResourceManager.GetString("Profile:NewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таҷрибаи нав.
        /// </summary>
        internal static string Profile_NewExperience {
            get {
                return ResourceManager.GetString("Profile:NewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калидвожаи куҳна.
        /// </summary>
        internal static string Profile_OldPassword {
            get {
                return ResourceManager.GetString("Profile:OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маълумоти шахсӣ.
        /// </summary>
        internal static string Profile_PersonalInformation {
            get {
                return ResourceManager.GetString("Profile:PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рақами телефон тасдиқ нашудааст!.
        /// </summary>
        internal static string Profile_PhoneNumberisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:PhoneNumberisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳозир.
        /// </summary>
        internal static string Profile_Present {
            get {
                return ResourceManager.GetString("Profile:Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сабт кардан.
        /// </summary>
        internal static string Profile_Save {
            get {
                return ResourceManager.GetString("Profile:Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тағйиротро захира кунед.
        /// </summary>
        internal static string Profile_Savechanges {
            get {
                return ResourceManager.GetString("Profile:Savechanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забонро интихоб кунед.
        /// </summary>
        internal static string Profile_SelectLanguage {
            get {
                return ResourceManager.GetString("Profile:SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маҳоратҳо.
        /// </summary>
        internal static string Profile_Skills {
            get {
                return ResourceManager.GetString("Profile:Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ихтисос.
        /// </summary>
        internal static string Profile_Specialty {
            get {
                return ResourceManager.GetString("Profile:Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Санаи оғоз.
        /// </summary>
        internal static string Profile_StartDate {
            get {
                return ResourceManager.GetString("Profile:StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ба темаи торик гузаред.
        /// </summary>
        internal static string Profile_SwitchtoDarkTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ба темаи рӯшан гузаред.
        /// </summary>
        internal static string Profile_SwitchtoLightTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ба систем гузаред.
        /// </summary>
        internal static string Profile_Switchtosystem {
            get {
                return ResourceManager.GetString("Profile:Switchtosystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳолати CV барои номзадии шумо.
        /// </summary>
        internal static string Profile_ThestatusofyourCVforyourcandidacyis {
            get {
                return ResourceManager.GetString("Profile:ThestatusofyourCVforyourcandidacyis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Барои иваз кардани калидвожаи худ, гузарвожаи кӯҳнаи худро ворид кунед ва пас калидвожаи нави қавӣ эҷод кунед..
        /// </summary>
        internal static string Profile_Tochangeyourpassword_enteryouroldpassword_andthencreateanew_strongpassword_ {
            get {
                return ResourceManager.GetString("Profile:Tochangeyourpassword,enteryouroldpassword,andthencreateanew,strongpasswor" +
                        "d.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боз кӯшиш кунед.
        /// </summary>
        internal static string Profile_TryAgain {
            get {
                return ResourceManager.GetString("Profile:TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Донишгоҳ.
        /// </summary>
        internal static string Profile_University {
            get {
                return ResourceManager.GetString("Profile:University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to То ҳозир.
        /// </summary>
        internal static string Profile_UntilNow {
            get {
                return ResourceManager.GetString("Profile:UntilNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навсозӣ.
        /// </summary>
        internal static string Profile_Update {
            get {
                return ResourceManager.GetString("Profile:Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV-ро боргузорӣ кунед.
        /// </summary>
        internal static string Profile_UploadCV {
            get {
                return ResourceManager.GetString("Profile:UploadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV-и навро боргузорӣ кунед.
        /// </summary>
        internal static string Profile_UploadNewCV {
            get {
                return ResourceManager.GetString("Profile:UploadNewCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ивази калидвожа.
        /// </summary>
        internal static string ResetPassword_Changepassword {
            get {
                return ResourceManager.GetString("ResetPassword:Changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калидвожаи Нав.
        /// </summary>
        internal static string ResetPassword_NewPassword {
            get {
                return ResourceManager.GetString("ResetPassword:NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рақами мобилӣ.
        /// </summary>
        internal static string ResetPassword_PhoneNumber {
            get {
                return ResourceManager.GetString("ResetPassword:PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рамзи дубора фиристед.
        /// </summary>
        internal static string ResetPassword_Resendcode {
            get {
                return ResourceManager.GetString("ResetPassword:Resendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рамзи тасдиқро фиристед.
        /// </summary>
        internal static string ResetPassword_Sendconfirmationcode {
            get {
                return ResourceManager.GetString("ResetPassword:Sendconfirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бекор кардан.
        /// </summary>
        internal static string SendCV_Close {
            get {
                return ResourceManager.GetString("SendCV:Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паёми шумо.
        /// </summary>
        internal static string SendCV_CoverLetter {
            get {
                return ResourceManager.GetString("SendCV:CoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV-и худро ба мо фиристед.
        /// </summary>
        internal static string SendCV_Title {
            get {
                return ResourceManager.GetString("SendCV:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи шумо.
        /// </summary>
        internal static string SendCV_Your_name {
            get {
                return ResourceManager.GetString("SendCV:Your name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to номери телефони шумо.
        /// </summary>
        internal static string SendCV_Your_phone_number {
            get {
                return ResourceManager.GetString("SendCV:Your phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳисоботи шумо вуҷуд надорад? Ба.
        /// </summary>
        internal static string SignIn_LabelDontAccount {
            get {
                return ResourceManager.GetString("SignIn:LabelDontAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калимаи убуратонро фаромуш кардед?.
        /// </summary>
        internal static string SignIn_LabelForgot {
            get {
                return ResourceManager.GetString("SignIn:LabelForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Бозгузории калимаи убур.
        /// </summary>
        internal static string SignIn_LinkReset {
            get {
                return ResourceManager.GetString("SignIn:LinkReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бақайдгирӣ.
        /// </summary>
        internal static string SignIn_LinkSignUp {
            get {
                return ResourceManager.GetString("SignIn:LinkSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калимаи убур.
        /// </summary>
        internal static string SignIn_Password {
            get {
                return ResourceManager.GetString("SignIn:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ворид шудан.
        /// </summary>
        internal static string SignIn_SignIn {
            get {
                return ResourceManager.GetString("SignIn:SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи корбар.
        /// </summary>
        internal static string SignIn_UserName {
            get {
                return ResourceManager.GetString("SignIn:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тасдиқ кардан.
        /// </summary>
        internal static string SignUp_Apply {
            get {
                return ResourceManager.GetString("SignUp:Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ба пеш.
        /// </summary>
        internal static string SignUp_ButtonNext {
            get {
                return ResourceManager.GetString("SignUp:ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string SignUp_Code {
            get {
                return ResourceManager.GetString("SignUp:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калидвожаро Тасдиқ Кунед.
        /// </summary>
        internal static string SignUp_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тасдиқи калимаи убур.
        /// </summary>
        internal static string SignUp_ConfirmPassword_HelperText {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почтаи электронӣ.
        /// </summary>
        internal static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp:Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идома бо.
        /// </summary>
        internal static string SignUp_ExternalLoginCard {
            get {
                return ResourceManager.GetString("SignUp:ExternalLoginCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ном.
        /// </summary>
        internal static string SignUp_FirstName {
            get {
                return ResourceManager.GetString("SignUp:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи худро ворид кунед.
        /// </summary>
        internal static string SignUp_FirstName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:FirstName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳисоботи шумо вуҷуд дорад? .
        /// </summary>
        internal static string SignUp_LabelHaveAccount {
            get {
                return ResourceManager.GetString("SignUp:LabelHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бақайдгирӣ.
        /// </summary>
        internal static string SignUp_LabelSignUp {
            get {
                return ResourceManager.GetString("SignUp:LabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насаб.
        /// </summary>
        internal static string SignUp_LastName {
            get {
                return ResourceManager.GetString("SignUp:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насаби худро ворид кунед.
        /// </summary>
        internal static string SignUp_LastName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:LastName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ворид шудан.
        /// </summary>
        internal static string SignUp_LinkSignIn {
            get {
                return ResourceManager.GetString("SignUp:LinkSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мо ба ин рақам коди тасдиқро фиристодем: $phone$. Лутфан, шиносоии худро тасдиқ кунед.
        /// </summary>
        internal static string signUp_messageText {
            get {
                return ResourceManager.GetString("signUp:messageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калимаи убур.
        /// </summary>
        internal static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калимаи убур.
        /// </summary>
        internal static string SignUp_Password_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Password_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string SignUp_Phone {
            get {
                return ResourceManager.GetString("SignUp:Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рақами телефони худро ворид кунед.
        /// </summary>
        internal static string SignUp_Phone_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Phone_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кодро боз фиристонидан.
        /// </summary>
        internal static string SignUp_ResendCode {
            get {
                return ResourceManager.GetString("SignUp:ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сония барои боз фиристодани код боқӣ мондааст..
        /// </summary>
        internal static string SignUp_Secconds {
            get {
                return ResourceManager.GetString("SignUp:Secconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи корбар.
        /// </summary>
        internal static string SignUp_UserName {
            get {
                return ResourceManager.GetString("SignUp:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Машваратхо.
        /// </summary>
        internal static string Trainings_Trainings {
            get {
                return ResourceManager.GetString("Trainings:Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҷавобҳо.
        /// </summary>
        internal static string UserButton_Applications {
            get {
                return ResourceManager.GetString("UserButton:Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баромад.
        /// </summary>
        internal static string UserButton_Logout {
            get {
                return ResourceManager.GetString("UserButton:Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хуҷраи шахсӣ.
        /// </summary>
        internal static string UserButton_Profile {
            get {
                return ResourceManager.GetString("UserButton:Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воридшавӣ.
        /// </summary>
        internal static string UserButton_Sign_In {
            get {
                return ResourceManager.GetString("UserButton:Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бақайдгирӣ.
        /// </summary>
        internal static string UserButton_Sign_Up {
            get {
                return ResourceManager.GetString("UserButton:Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳама.
        /// </summary>
        internal static string VacanciesList_All {
            get {
                return ResourceManager.GetString("VacanciesList:All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Муддати бақайдгирӣ.
        /// </summary>
        internal static string VacanciesList_Deadline {
            get {
                return ResourceManager.GetString("VacanciesList:Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давомият.
        /// </summary>
        internal static string VacanciesList_Duration {
            get {
                return ResourceManager.GetString("VacanciesList:Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Санаи тамоми.
        /// </summary>
        internal static string VacanciesList_End_date {
            get {
                return ResourceManager.GetString("VacanciesList:End date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to моҳ(ҳо).
        /// </summary>
        internal static string VacanciesList_month_s_ {
            get {
                return ResourceManager.GetString("VacanciesList:month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳоло вазифаҳо барои кор дастрас намешаванд. Илтимос баъдтар санҷед :).
        /// </summary>
        internal static string VacanciesList_NoJobs {
            get {
                return ResourceManager.GetString("VacanciesList:NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нашр шудааст.
        /// </summary>
        internal static string VacanciesList_Posted {
            get {
                return ResourceManager.GetString("VacanciesList:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҷустуҷӯ.
        /// </summary>
        internal static string VacanciesList_Search {
            get {
                return ResourceManager.GetString("VacanciesList:Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тафсилоти иловагӣ.
        /// </summary>
        internal static string VacancyApplication_Additional_Details {
            get {
                return ResourceManager.GetString("VacancyApplication:Additional Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истифода баред.
        /// </summary>
        internal static string VacancyApplication_Apply {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истифодабарандагии профили худро истифода баред.
        /// </summary>
        internal static string VacancyApplication_Apply_using_profile {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply using profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истифодаи файл боркуни.
        /// </summary>
        internal static string VacancyApplication_Apply_with_uploading_file {
            get {
                return ResourceManager.GetString("VacancyApplication:Apply with uploading file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи пешниҳод.
        /// </summary>
        internal static string VacancyApplication_Cover_Letter {
            get {
                return ResourceManager.GetString("VacancyApplication:Cover Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Муддати бақайдгирӣ.
        /// </summary>
        internal static string VacancyApplication_Deadline {
            get {
                return ResourceManager.GetString("VacancyApplication:Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давомият.
        /// </summary>
        internal static string VacancyApplication_Duration {
            get {
                return ResourceManager.GetString("VacancyApplication:Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Санаи тамоми.
        /// </summary>
        internal static string VacancyApplication_End_Date {
            get {
                return ResourceManager.GetString("VacancyApplication:End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суҳбат.
        /// </summary>
        internal static string VacancyApplication_Fees {
            get {
                return ResourceManager.GetString("VacancyApplication:Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to моҳ(ҳо).
        /// </summary>
        internal static string VacancyApplication_month_s_ {
            get {
                return ResourceManager.GetString("VacancyApplication:month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовано.
        /// </summary>
        internal static string VacancyApplication_Posted {
            get {
                return ResourceManager.GetString("VacancyApplication:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коркард.
        /// </summary>
        internal static string VacancyApplication_Processing {
            get {
                return ResourceManager.GetString("VacancyApplication:Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Саволҳо.
        /// </summary>
        internal static string VacancyApplication_Questions {
            get {
                return ResourceManager.GetString("VacancyApplication:Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Талаботи солҳои таҷриба.
        /// </summary>
        internal static string VacancyApplication_Required_year_of_experience {
            get {
                return ResourceManager.GetString("VacancyApplication:Required year of experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резюмеи худро бор кунед.
        /// </summary>
        internal static string VacancyApplication_Upload_your_CV {
            get {
                return ResourceManager.GetString("VacancyApplication:Upload your CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тафсилоти вазифа.
        /// </summary>
        internal static string VacancyApplication_Vacancy_Details {
            get {
                return ResourceManager.GetString("VacancyApplication:Vacancy Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сол(ҳо).
        /// </summary>
        internal static string VacancyApplication_year_s_ {
            get {
                return ResourceManager.GetString("VacancyApplication:year(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунти шумо аллакай мавҷуд аст?.
        /// </summary>
        internal static string VacancyDetails_Already_have_an_account_ {
            get {
                return ResourceManager.GetString("VacancyDetails:Already have an account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳозир интихоб кунед.
        /// </summary>
        internal static string VacancyDetails_Apply_Now {
            get {
                return ResourceManager.GetString("VacancyDetails:Apply Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оё шумо тайёрӣ доред, карьераро ба дараёи зирзамини оянда гиред бо.
        /// </summary>
        internal static string VacancyDetails_Are_you_ready_to_take_your_career_to_the_next_level_with {
            get {
                return ResourceManager.GetString("VacancyDetails:Are you ready to take your career to the next level with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Муддати бақайдгирӣ.
        /// </summary>
        internal static string VacancyDetails_Deadline {
            get {
                return ResourceManager.GetString("VacancyDetails:Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV-ро зеркашӣ кунед.
        /// </summary>
        internal static string VacancyDetails_Download_CV {
            get {
                return ResourceManager.GetString("VacancyDetails:Download CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давомият.
        /// </summary>
        internal static string VacancyDetails_Duration {
            get {
                return ResourceManager.GetString("VacancyDetails:Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тамомшавии муддат.
        /// </summary>
        internal static string VacancyDetails_End_Date {
            get {
                return ResourceManager.GetString("VacancyDetails:End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таҳлили.
        /// </summary>
        internal static string VacancyDetails_Explore {
            get {
                return ResourceManager.GetString("VacancyDetails:Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хизмати пулидан.
        /// </summary>
        internal static string VacancyDetails_Fees {
            get {
                return ResourceManager.GetString("VacancyDetails:Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to моҳ(ҳо).
        /// </summary>
        internal static string VacancyDetails_month_s_ {
            get {
                return ResourceManager.GetString("VacancyDetails:month(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to имкониятҳо.
        /// </summary>
        internal static string VacancyDetails_opportunities {
            get {
                return ResourceManager.GetString("VacancyDetails:opportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовано.
        /// </summary>
        internal static string VacancyDetails_Posted {
            get {
                return ResourceManager.GetString("VacancyDetails:Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Талаботи солҳои тажриба.
        /// </summary>
        internal static string VacancyDetails_Required_year_of_experience {
            get {
                return ResourceManager.GetString("VacancyDetails:Required year of experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ворид шавед.
        /// </summary>
        internal static string VacancyDetails_Sign_In {
            get {
                return ResourceManager.GetString("VacancyDetails:Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бақайдгирӣ кунед.
        /// </summary>
        internal static string VacancyDetails_Sign_Up {
            get {
                return ResourceManager.GetString("VacancyDetails:Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мутасиршудагӣ, муддат аллакай гузашт.
        /// </summary>
        internal static string VacancyDetails_Unfortunately__the_deadline_has_already_expired {
            get {
                return ResourceManager.GetString("VacancyDetails:Unfortunately, the deadline has already expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нависед суроғаи муваффақ, якчанд савол ҷавоб диҳед ва сабти зарафшониро рўй бедиҳед!.
        /// </summary>
        internal static string VacancyDetails_Write_a_cover_letter__answer_few_questions_and_send_your_application_ {
            get {
                return ResourceManager.GetString("VacancyDetails:Write a cover letter, answer few questions and send your applicati" +
                        "on!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сол(ҳо).
        /// </summary>
        internal static string VacancyDetails_year_s_ {
            get {
                return ResourceManager.GetString("VacancyDetails:year(s)", resourceCulture);
            }
        }
    }
}
