name: Publish image to Azure
on:
  push:
    branches: [ "staging" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Minor version for each merge
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.64.0
        env:
          WITH_V: true
          DRY_RUN: true
      
      
      # - name: build docker image for Web API
      #   run: |
      #     docker build -t silkroadprofessionals.azurecr.io/mra-web-api:${{ steps.taggerDryRun.outputs.new_tag }} .
      #   working-directory: ./src

      # - name: Publish Web API to ACR
      #   run: |
      #     docker login silkroadprofessionals.azurecr.io -u silkroadprofessionals -p ${{ secrets.ACR_PASS }}
      #     docker push silkroadprofessionals.azurecr.io/mra-web-api:${{ steps.taggerDryRun.outputs.new_tag }}

      - name: Update infrastructure image version
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: update
          token: ${{ secrets.GH_TOKEN }}
          repository: srp-internships/MRAInfrastructure
          client-payload: '{"version":"${{ steps.taggerDryRun.outputs.new_tag }}", "environment":"Staging", "image":"mra-web-api"}'

      - name: Minor version for each merge
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true