name: Publish image to Docker Hub

on: push

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.patch }}

      - name: build docker image for Identity Service
        run: |
          docker build . -t adheem/mra-identity-api:${{ steps.semvers.outputs.patch }}
        working-directory: ./src/MRA.Jobs.Identity

      - name: Publish Identity Service to Docker Hub
        run: |
          docker login -u adheem -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push adheem/mra-identity-api:${{ steps.semvers.outputs.patch }}


