name: Publish image to Docker Hub

on: push

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Minor version for each merge
      id: taggerDryRun
      uses: anothrNick/github-tag-action@1.36.0
      env:
        WITH_V: true
        DRY_RUN: true

      - name: build docker image for Identity Service
        run: |
          docker build . -t adheem/mra-identity-api:${{ steps.taggerDryRun.outputs.new_tag }}
        working-directory: ./src/MRA.Jobs.Identity

      - name: Publish Identity Service to Docker Hub
        run: |
          docker login -u adheem -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push adheem/mra-identity-api:${{ steps.taggerDryRun.outputs.new_tag }}


